# Generated by Django 5.1.7 on 2026-02-02 22:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueblesapp', '0002_empresa_inmueble_create_inmueble_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
