# Generated by Django 5.1.7 on 2026-02-02 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmueblesapp', '0003_empresa_create_empresa_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='nombre',
        ),
    ]
