# Generated by Django 5.1.7 on 2026-02-03 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmueblesapp', '0004_remove_inmueble_nombre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inmueble',
            new_name='Edificacion',
        ),
    ]
