# Generated by Django 5.1.7 on 2026-02-03 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueblesapp', '0005_rename_inmueble_edificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificacion',
            name='empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='edificacion', to='inmueblesapp.empresa'),
            preserve_default=False,
        ),
    ]
