# Generated by Django 5.1.7 on 2026-02-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueblesapp', '0008_comentario_comentario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificacion',
            name='avg_calificacion',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='edificacion',
            name='number_calificacion',
            field=models.IntegerField(default=0),
        ),
    ]
